cash:
    path:     /
    defaults: { _controller: "BackendBundle:Cash:index" }

cash_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Cash:show" }

cash_timeline:
    path:     /{id}/timeline
    defaults: { _controller: "BackendBundle:Cash:timeline" }

cash_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Cash:new" }

cash_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Cash:create" }
    requirements: { _method: post }

cash_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Cash:edit" }

cash_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Cash:update" }
    requirements: { _method: post|put }

cash_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Cash:delete" }

cash_reporte_por_rango_de_fechas:
    path:     /{banking}/pdf
    defaults: { _controller: "BackendBundle:Cash:generarReportePDF" }


