extra:
    path:     /
    defaults: { _controller: "BackendBundle:Extra:index" }

extra_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Extra:show" }

extra_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Extra:new" }

extra_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Extra:create" }
    requirements: { _method: post }

extra_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Extra:edit" }

extra_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Extra:update" }
    requirements: { _method: post|put }

extra_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Extra:delete" }
    requirements: { _method: post|delete }


extra_filter:
    path:     /filtrar
    defaults: { _controller: "BackendBundle:Extra:filtrar" }